---
name: Lint

on:
  push:
  pull_request:

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # REQUIRED for v8+
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main

          # DISABLE EVERYTHING YOU DON'T USE
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_CHECKOV: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_JAVA: false
          VALIDATE_JAVA_FORMAT: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_RUFF_FORMAT: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false

          # KEEP ONLY WHAT YOU WANT
          VALIDATE_YAML: true
